- hosts: all
  become: yes
  tasks:
    - name: Disabling swap
      shell: swapoff -a

    - name: Install gnupg
      apt:
        name: gnupg2
        state: present

    - name: Install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present

    - name: Install CA Certificates
      apt:
        name: ca-certificates
        state: present

    - name: Install Software Properties Common
      apt:
        name: software-properties-common
        state: present

    - name: Install bridge-utils
      apt:
        name: bridge-utils
        state: present

    - name: Starting overlay module
      command: modprobe overlay

    - name: Starting br_netfilter
      command: modprobe br_netfilter

    - name: Create Kubernetes Config
      copy:
        dest: "/etc/sysctl.d/kubernetes.conf"
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1

    - name: Restarting sysctl
      command: sysctl --system

    - name: Add Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'

    - name: Install kubernetes-cni
      apt:
        name: kubernetes-cni
        state: present
        update_cache: true

    - name: Install kubelet
      apt:
        name: kubelet
        state: present
        update_cache: true

    - name: Install kubeadm
      apt:
        name: kubeadm
        state: present
        update_cache: true

    - name: Install kubectl
      apt:
        name: kubectl
        state: present
        update_cache: true
        force: yes

    - name: Create containerd config
      copy:
        dest: "/etc/modules-load.d/containerd.conf"
        content: |
          overlay
          br_netfilter

    - name: Install containerd
      apt:
        name: containerd
        state: present
        update_cache: true

    - name: Create containerd directory
      file:
        path: /etc/containerd
        state: directory
        mode: 0755

    - name: Configure containerd
      shell: containerd config default | tee /etc/containerd/config.toml

    - name: Setup containerd service, daemon reload
      command: systemctl daemon-reload

    - name: Setup containerd service, restart
      command: systemctl restart containerd

    - name: Setup containerd service, enable
      command: systemctl enable containerd


- hosts: devel
  become: yes
  tasks:
    - name: Add Docker apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Setup Docker service
      command: systemctl enable docker.service
