- hosts: control-plane
  become: yes
  gather_facts: false
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: nodes
  become: yes
  tasks:
    - name: Disabling swap
      shell: swapoff -a

    - name: Join cluster
      shell: "{{ hostvars['control-plane'].join_command }}"

- hosts: control-plane
  gather_facts: false
  tasks:
    - name: Setting nodes active
      shell: kubectl taint nodes "{{ hostvars[item].ansible_fqdn }}" node.kubernetes.io/not-ready:NoSchedule-
      with_items: "{{ groups['nodes'] }}"
